---
include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: 
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

variables:
  IMAGE: "tulibraries/tul-hyku"
  HARBOR: "harbor.k8s.temple.edu"
  HYKU: "ghcr.io/samvera/hyku"
  HELM_EXPERIMENTAL_OCI: "1"

before_script:
  - export TAG=${CI_COMMIT_SHORT_SHA}
  - export BRANCH=${CI_COMMIT_REF_NAME}

stages:
  - build
  - scan
  - tag
  - deploy

build:
  stage: build
  script:
    - docker-compose build web
    - docker-compose build worker
    - docker tag ${HYKU}  "${HARBOR}/${IMAGE}/web:${VERSION}"
    - docker tag "${HYKU}/worker"  "${HARBOR}/${IMAGE}/worker:${VERSION}"
    - docker-compose push "${HARBOR}/${IMAGE}/web:${VERSION}"
    - docker-compose push  "${HARBOR}/${IMAGE}/worker:${VERSION}"

hyku.dev:
  stage: deploy
  extends:
    - .deploy
  environment:
    name: hyku.dev
    url: http://hyku-dev.example.com
  only:
    refs:
      - main
  variables:
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE
    DEPLOY_TAG: $CI_COMMIT_SHORT_SHA
    WORKER_IMAGE: $CI_REGISTRY_IMAGE/worker
    HELM_EXPERIMENTAL_OCI: 1
    HELM_EXTRA_ARGS: >
      --values ops/dev-deploy.yaml
  script:
    - envsubst < ops/dev-deploy.tmpl.yaml > ops/dev-deploy.yaml
    - ./bin/helm_deploy hyku-dev dev
  tags:
    - kubernetes

hyku.production:
  stage: deploy
  extends:
    - .deploy
  environment:
    name: hyku.production
    url: http://hyku-production.example.com
  only:
    refs:
      - main
  when: manual
  variables:
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE
    DEPLOY_TAG: $CI_COMMIT_SHORT_SHA
    WORKER_IMAGE: $CI_REGISTRY_IMAGE/worker
    HELM_EXPERIMENTAL_OCI: 1
    HELM_EXTRA_ARGS: >
      --values ops/production-deploy.yaml
  script:
    - envsubst < ops/production-deploy.tmpl.yaml > ops/production-deploy.yaml
    - ./bin/helm_deploy hyku-production production
  tags:
    - kubernetes

.deploy:
  image: dtzar/helm-kubectl:3.5.3
