---
include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: 
      - "build_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

variables:
  IMAGE: "tulibraries/tul-hyku"
  HARBOR: "harbor.k8s.temple.edu"
  HYKU: "ghcr.io/samvera/hyku"
  HELM_EXPERIMENTAL_OCI: "1"

before_script:
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

stages:
  - build
  - scan
  - deploy

build:
  stage: build
  extends: .build_image
  image: $HARBOR/gitlab-ci/docker:latest
  services:
    - name: $HARBOR/gitlab-ci/docker:23-dind
    - command: ["--tls=false"]
  script:
    - *check_atc_harbor
    - docker info
    - echo "$HARBOR_TOKEN" | docker login -u $HARBOR_USERNAME --password-stdin $HARBOR
    - docker-compose build web
    - docker-compose build worker
    - docker tag ${HYKU}  "${HARBOR}/${IMAGE}/web:${VERSION}"
    - docker tag "${HYKU}/worker"  "${HARBOR}/${IMAGE}/worker:${VERSION}"
    - docker tag ${HYKU}  "${HARBOR}/${IMAGE}/web:latest"
    - docker tag "${HYKU}/worker"  "${HARBOR}/${IMAGE}/worker:latest"
    - docker push "${HARBOR}/${IMAGE}/web:${VERSION}"
    - docker push "${HARBOR}/${IMAGE}/worker:${VERSION}"

scan:
  stage: scan
  extends: .scanimage_high
  allow_failure: true
  variables:
    THRESHOLD: 10
  except:
    - tags
