version: 2.1
orbs:
  samvera: samvera/circleci-orb@1
  browser-tools: circleci/browser-tools@1.3
  ruby: circleci/ruby@2
  node: circleci/node@5

jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.7.8
      bundler_version:
        type: string
        default: 2.4.8
      rails_version:
        type: string
        default: '5.1.6'
      solr_config_path:
        type: string
      fcrepo_version:
        type: string
        default: '4.7'
      solr_port:
        type: string
        default: '8985'
      redis_version:
        type: string
        default: '4'
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>-browsers
      - image: ualbertalib/docker-fcrepo4:<< parameters.fcrepo_version>>
        environment:
          CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
      - image: bitnami/solr:8
        environment:
          SOLR_PORT_NUMBER: 8985
          SOLR_CLOUD_BOOTSTRAP: "yes"
          SOLR_ENABLE_CLOUD_MODE: "yes"
          SOLR_ENABLE_AUTHENTICATION: "yes"
          SOLR_COLLECTION: hydra-test
          SOLR_ADMIN_USER: admin
          SOLR_ADMIN_PASSWORD: admin
          SOLR_ZK_HOSTS: localhost
      - image: bitnami/zookeeper
        environment:
           ALLOW_ANONYMOUS_LOGIN: "yes"
           JVMFLAGS: -Dzookeeper.4lw.commands.whitelist=ruok -Dzookeeper.admin.enableServer=false
           ZOO_SERVERS: zoo1:2888:3888
           ZOO_ADMIN_SERVER_PORT_NUMBER: 8020
      - image: circleci/redis:<<parameters.redis_version>>
      - image: circleci/postgres:9.6.2-alpine
    parallelism: 4
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      DB_NAME: circle_test
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_TEST_NAME: circle_test
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      HYKU_RESTRICT_CREATE_AND_DESTROY_PERMISSIONS: 'true'
      SOLR_ADMIN_USER: admin
      SOLR_ADMIN_PASSWORD: admin
      SOLR_COLLECTION_NAME: hydra-test
      SOLR_CONFIGSET_NAME: hyku
      SOLR_HOST: localhost
      SOLR_PORT: 8985
      SOLR_URL: http://admin:admin@localhost:8985/solr/
      RAILS_ENV: test
      RACK_ENV: test
      FCREPO_TEST_PORT: 8080/fcrepo
      SPEC_OPTS: --tag ~ci:skip --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    steps:
      - samvera/cached_checkout
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      - samvera/rubocop
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome install
          command: |
            google-chrome --version
            chromedriver --version
      - run: bundle exec rake db:create db:schema:load
      - run: bin/solrcloud-upload-configset.sh solr/conf
      - samvera/parallel_rspec
      - store_artifacts:
          path: coverage
workflows:
  ci:
    jobs:
      - bundle:
          ruby_version: "2.7.8"
          name: "ruby2-7-8"
          solr_config_path: 'solr/conf'
