# Hi - please dont edit this file directly, instead make changes in your .env file

login: &login
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  schema_search_path: "public,shared_extensions"
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] || 'hyku' %>
  pool: 50
  timeout: 5000
  prepared_statements: <%= ENV.fetch('DB_PREPARED_STATEMENTS', true) %>
  advisory_locks: <%= ENV.fetch('DB_ADVISORY_LOCKS', true) %>

development:
  <<: *login

test:
  <<: *login
  database: <%= ENV['DB_TEST_NAME'] || 'hyku_test' %>

staging:
  <<: *login


production:
  <<: *login
