default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  image_uploadtab: true
  toolbar1: styleselect fontselect fontsizeselect | backcolor forecolor | bold italic underline
  toolbar2: indent outdent | alignleft aligncenter alignright | table | fullscreen | link hr image | undo redo  | code
  plugins:
    - table
    - fullscreen
    - link
    - autolink
    - image
    - code
custom:
  <<: *default
